# Generated by Django 3.0.5 on 2023-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(max_length=20),
        ),
    ]
