# Generated by Django 3.0.5 on 2024-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20230814_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologists'), ('Emergency Medicine Specialist', 'Emergency Medicine Specialists'), ('Allergist/Immunologist', 'Allergists/Immunologists'), ('Anesthesiologist', 'Anesthesiologists'), ('Colon and Rectal Surgeon', 'Colon and Rectal Surgeons'), ('paediatrician', 'paediatricians')], default='Cardiologist', max_length=50),
        ),
    ]
